# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='fun_facts',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, null=True, to='m_maps.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='m_maps.Location'),
        ),
    ]
