# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-03 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='director',
            name='director',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='distributor',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='production_company',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='releaseyear',
            name='year',
            field=models.CharField(db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
