# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_maps', '0002_auto_20160705_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(to='m_maps.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='location',
            field=models.ManyToManyField(to='m_maps.Location'),
        ),
    ]
