# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_maps', '0003_auto_20160705_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='fun_facts',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
