# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_maps', '0004_auto_20160705_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='director',
            name='director',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='distributor',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='production_company',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
